name: "deploy-ec2-instance"
description: "Deploy an EC2 instance using a Terraform module."
terraform_module: "https://github.com/yourorg/terraform-aws-ec2-instance.git"
auto_detect_vars: true
env:
  - AWS_ACCESS_KEY_ID
  - AWS_SECRET_ACCESS_KEY
  - AWS_DEFAULT_REGION
  - GH_TOKEN
secrets:
  - AWS_ACCESS_KEY_ID
  - AWS_SECRET_ACCESS_KEY
  - GH_TOKEN 