name: "vpc"
description: "AWS VPC Module for creating networking infrastructure"

# Source configuration
source:
  # Can be a git URL or local path
  location: "https://github.com/terraform-aws-modules/terraform-aws-vpc.git"
  type: "git"  # git or local
  git_config:
    ref: "v3.0.0"  # Branch, tag, or commit
    subfolder: "examples/complete"  # Optional, for nested modules
  
# Optional pre-script to run before Terraform operations
pre_script: |
  #!/bin/bash
  echo "Preparing environment..."

# Environment variables needed
env:
  - AWS_ACCESS_KEY_ID
  - AWS_SECRET_ACCESS_KEY
  - AWS_DEFAULT_REGION
  - GH_TOKEN

# Required secrets
secrets:
  - AWS_ACCESS_KEY_ID
  - AWS_SECRET_ACCESS_KEY
  - GH_TOKEN

# Optional variable overrides or constraints
variable_overrides:
  vpc_name:
    description: "Override default description"
    type: "string"
    required: true
  environment:
    allowed_values: ["dev", "staging", "prod"]