name: Build and push chat-ui

on:
  push:
    branches-ignore:
      - main
      - production
      - staging
      - demo
      - release-*

env:
  environment: dev

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set BRANCH_NAME
        run: echo "BRANCH_NAME=$(echo ${GITHUB_REF#refs/heads/})" >> $GITHUB_ENV


      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-region: eu-west-1
          role-to-assume: arn:aws:iam::564407622114:role/github-action-role

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        with:
          context: ./kubiya-chat
          file: ./kubiya-chat/Dockerfile
          push: true
          tags: |
            "564407622114.dkr.ecr.eu-west-1.amazonaws.com/chat-ui:${{ github.actor }}"
            "564407622114.dkr.ecr.eu-west-1.amazonaws.com/chat-ui:${{ github.sha }}"
          platforms: linux/amd64,linux/arm64
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: Checkout deployments repository
        uses: actions/checkout@v3
        with:
          repository: kubiyabot/deployments
          ref: main
          token: ${{ secrets.KUBIYA_GITHUB_TOKEN }}

      - name: Update ArgoCD values file and push to ${{ env.environment }} by ${{ github.actor }}
        env:
          GITHUB_TOKEN: ${{ secrets.KUBIYA_GITHUB_TOKEN }}
        run: |
          yq e '.chat-ui.image.tag = "${{ github.sha }}"' -i helm/kubiya-server/values.${{ github.actor }}.yaml
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          COMMIT_MSG="Update $GITHUB_REPOSITORY image tag to $GITHUB_SHA for $environment by $GITHUB_ACTOR"
          git commit -am "$COMMIT_MSG"
          git push
