on:
  push:
    branches:
      - production
      # - DEV-*

name: Build and Deploy Next.js to S3 - Production

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [20.x]

    steps:
      - uses: actions/checkout@v2

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install Dependencies
        run: |
          cd kubiya-chat
          npm install

      - name: Build Next.js Application
        env:
          NEXT_PUBLIC_KUBIYA_API_KEY: ${{ secrets.NEXT_PUBLIC_KUBIYA_API_KEY }}
        run: |
          cd kubiya-chat
          npm run build

      - name: Upload to S3
        run: |
          ls -la
          cd kubiya-chat
          ls -la
          aws s3 sync .next s3://chat-kubiya-ai-production/
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: "us-east-1"

      - name: Invalidate CloudFront Cache
        run: |
          aws cloudfront create-invalidation \
          --distribution-id E2UEUTJUXML42Z \
          --paths "/*"
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: "us-east-1"
